### PR TITLE
switch to colored itemstacks

### PR DESCRIPTION
**Pull request by VanessaE**
with full crafting recipes
(requires Unified Dyes commit 2a816534 or later)

### CODE REVIEW

**Review by SmallJoker — APPROVED** [review]
Looks good

**Comment by VanessaE** [comment]
What?  How did this get closed? :open_mouth:

**Comment by SmallJoker** [comment]
You created a new PR #5

**Comment by VanessaE** [comment]
Oh ffs.  Herp.  derp..

**Pull request closed without merging**
