### PR TITLE
Use "mod.conf", delete "depends.txt" and "description.txt"

### PR DESCRIPTION
**Pull request by Panquesito7**
This will make it only compatible with MT/MTG 5.0.0+.

### CODE REVIEW

**Comment by Panquesito7** [comment]
@sofar.

**Comment by mckaygerhard** [comment]
some servers still use MT 0.4

**Comment by Panquesito7** [comment]
> some servers still use MT 0.4

They can keep the old version, plus someday it's gonna get deprecated.

**Comment by mckaygerhard** [comment]
as we can see in the forums.. and MT server list.. the two only 0.4.17 servers onlyne are the second and third most played after catlandia.. and only cos the my was shutdown to migrate auth mechanish.. but i will use again 0.4 cos it seems more better... in fact my 0.4.17 server is more played rather than any 5.0 so "deprecated" is only for MT 5.X fans that seems are only few desktops computers

**Comment by rollerozxa** [comment]
It's been 3 years now, maybe time to merge?

**Comment by Niklp09** [comment]
Done in https://github.com/minetest-mods/unifiedbricks/commit/1011023d6cb9f0cdc80bbdd7c9b7b2032a7f16d2

**Pull request closed without merging**
